#!/bin/bash

output_html=release/mathjax.html
output_cwl=release/texplates.cwl

# build mathjax.html
tex_cmds=$(cat \
    basics/macros.tex \
    basics/mathjax.tex \
) || exit 1

cat <<- EOF > "$output_html"
	<!-- mathjax for local use -->

	<div class="mathjax_macros" style="display: none;">
	\$ $tex_cmds \$
	</div>
EOF

# build texplates.cwl
./utils/tex2cwl basics/macros.tex > "$output_cwl"

git add --intent-to-add "$output_html" "$output_cwl"

if ! git diff --exit-code "$output_html" "$output_cwl"; then
    git add "$output_html" "$output_cwl"
    exit 1
fi
